FROM mysql:9.0.1

ENV MYSQL_ALLOW_EMPTY_PASSWORD yes

# COPY /mysql/setup.sh /mysql/setup.sh #拷贝安装脚本
# COPY /mysql/create_db.sql /mysql/create_db.sql #创建数据库
# COPY /mysql/initial_data.sql /mysql/initial_data.sql #初始数据
# COPY /mysql/privileges.sql /mysql/privileges.sql #设置密码和权限

EXPOSE 3306
# CMD ["sh", "/mysql/setup.sh"]