FROM node:16.14.0-alpine AS nodeimg
WORKDIR /briar-mono
COPY . .
RUN npm install -g pnpm@8.15.9
RUN pnpm install --production  
RUN pnpm run build
RUN pnpm run cdn

FROM node:16.14.0-alpine
WORKDIR /briar-mono
COPY --from=nodeimg /briar-mono/packages/briar-node /briar-mono/packages/briar-node
COPY --from=nodeimg /briar-mono/node_modules /briar-mono/node_modules
EXPOSE 8922
CMD ["pnpm", "run", "start"]





