FROM nginx:1.16.0-alpine
RUN rm /etc/nginx/conf.d/default.conf
RUN mkdir -p /usr/share/nginx/static
COPY /default.conf /etc/nginx/conf.d
COPY /assets/ssl/stardew.site_bundle.crt /etc/nginx
COPY /assets/ssl/stardew.site.key /etc/nginx
EXPOSE 443
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]



