name: Docker Compose CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # 在GitHub Secrets中设置你的Docker Hub用户名
          password: ${{ secrets.DOCKER_PASSWORD }} # 在GitHub Secrets中设置你的Docker Hub密码

      - name: Prune Docker system
        run: |
          docker system prune -a -f

      - name: Build and run using Docker Compose
        run: |
          docker compose up --build

      - name: Push images to Docker Hub
        run: |
          docker compose push
